import { useState, useCallback, useRef } from 'react';
import { ModuleLayout } from '@/components/ModuleLayout';
import { InfoBox } from '@/components/InfoBox';
import { Play, RotateCcw, Plus } from 'lucide-react';

interface ScaleNote {
  name: string;
  ratio: number;
  frequency: number;
  fifthsFromC: number;
}

// Order of notes generated by circle of fifths
const noteNames = ['Do', 'Sol', 'Re', 'La', 'Mi', 'Si', 'Fa#', 'Do#', 'Sol#', 'Re#', 'La#', 'Fa'];

const Module7 = () => {
  const [notes, setNotes] = useState<ScaleNote[]>([
    { name: 'Do', ratio: 1, frequency: 261.63, fifthsFromC: 0 }
  ]);
  const [activeNote, setActiveNote] = useState<number | null>(null);
  const audioContextRef = useRef<AudioContext | null>(null);

  const baseFrequency = 261.63; // C4

  const addFifth = useCallback(() => {
    if (notes.length >= 12) return;

    // Find the note with the highest fifthsFromC to continue the chain
    const lastInChain = notes.reduce((max, note) => 
      note.fifthsFromC > max.fifthsFromC ? note : max
    , notes[0]);
    
    // Calculate new ratio from the original Do, not from lastInChain
    // After n fifths from C: ratio = (3/2)^n, then bring into octave [1, 2)
    const fifthsCount = lastInChain.fifthsFromC + 1;
    let newRatio = Math.pow(1.5, fifthsCount);
    
    // Bring back into octave [1, 2)
    while (newRatio >= 2) {
      newRatio /= 2;
    }
    while (newRatio < 1) {
      newRatio *= 2;
    }

    const newName = noteNames[fifthsCount] || `Nota ${fifthsCount + 1}`;

    const newNote: ScaleNote = {
      name: newName,
      ratio: newRatio,
      frequency: baseFrequency * newRatio,
      fifthsFromC: fifthsCount,
    };

    setNotes(prev => [...prev, newNote].sort((a, b) => a.ratio - b.ratio));
  }, [notes]);

  const reset = () => {
    setNotes([{ name: 'Do', ratio: 1, frequency: 261.63, fifthsFromC: 0 }]);
  };

  const playNote = useCallback((frequency: number, index: number) => {
    if (!audioContextRef.current) {
      audioContextRef.current = new (window.AudioContext || (window as any).webkitAudioContext)();
    }
    const ctx = audioContextRef.current;

    const osc = ctx.createOscillator();
    const gain = ctx.createGain();

    osc.type = 'sine';
    osc.frequency.setValueAtTime(frequency, ctx.currentTime);
    gain.gain.setValueAtTime(0.3, ctx.currentTime);
    gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 0.5);

    osc.connect(gain);
    gain.connect(ctx.destination);
    osc.start();
    osc.stop(ctx.currentTime + 0.5);

    setActiveNote(index);
    setTimeout(() => setActiveNote(null), 500);
  }, []);

  const playScale = useCallback(() => {
    notes.forEach((note, i) => {
      setTimeout(() => playNote(note.frequency, i), i * 300);
    });
  }, [notes, playNote]);

  const formatRatio = (ratio: number): string => {
    // Common Pythagorean ratios
    const knownRatios: { value: number; label: string }[] = [
      { value: 1, label: '1' },
      { value: 3/2, label: '3/2' },
      { value: 9/8, label: '9/8' },
      { value: 27/16, label: '27/16' },
      { value: 81/64, label: '81/64' },
      { value: 243/128, label: '243/128' },
      { value: 729/512, label: '729/512' },
      { value: 4/3, label: '4/3' }, // Fa (from bringing 2187/2048 down, but simpler is 4/3)
      { value: 2187/2048, label: '2187/2048' },
      { value: 6561/4096, label: '6561/4096' },
      { value: 19683/16384, label: '19683/16384' },
      { value: 59049/32768, label: '59049/32768' },
    ];
    
    for (const known of knownRatios) {
      if (Math.abs(ratio - known.value) < 0.0001) {
        return known.label;
      }
    }
    return ratio.toFixed(4);
  };

  // Calculate position based on ratio (logarithmic scale for better visualization)
  const getPosition = (ratio: number): number => {
    // Use log scale: position = log2(ratio) / log2(2) * 100 = log2(ratio) * 100
    return (Math.log2(ratio) / Math.log2(2)) * 90 + 2; // 2-92% range
  };

  return (
    <ModuleLayout
      moduleNumber={7}
      title="Costruire la scala con le quinte"
      description="Usa solo il rapporto 3/2 per costruire tutte le note della scala musicale. È matematica pura!"
      prevModule={{ path: '/modulo-6', title: 'Ottava' }}
      nextModule={{ path: '/modulo-8', title: 'Dominante' }}
    >
      <div className="space-y-8">
        {/* Building interface */}
        <div className="module-card">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-display text-xl font-semibold">
              Costruisci la scala
            </h3>
            <span className="info-badge">
              {notes.length}/12 note
            </span>
          </div>
          
          <p className="text-muted-foreground mb-6">
            Parti dal Do e moltiplica per 3/2 (la quinta). Se superi l'ottava, dividi per 2 per tornare indietro.
          </p>

          {/* Notes visualization */}
          <div className="relative mb-6">
            {/* Frequency line with labels */}
            <div className="flex justify-between text-xs text-muted-foreground mb-1">
              <span>Do (1)</span>
              <span>Do₂ (2)</span>
            </div>
            <div className="h-2 bg-muted rounded-full mb-4" />
            
            {/* Note markers */}
            <div className="relative h-28">
              {notes.map((note, i) => {
                const position = getPosition(note.ratio);
                return (
                  <button
                    key={`${note.name}-${i}`}
                    onClick={() => playNote(note.frequency, i)}
                    className={`absolute transform -translate-x-1/2 transition-all ${
                      activeNote === i ? 'scale-125 z-10' : 'hover:scale-110'
                    }`}
                    style={{ left: `${position}%` }}
                  >
                    <div className={`w-12 h-12 rounded-xl flex items-center justify-center text-sm font-bold ${
                      activeNote === i 
                        ? 'bg-accent text-white shadow-glow' 
                        : 'bg-primary text-primary-foreground'
                    }`}>
                      {note.name}
                    </div>
                    <div className="text-xs text-muted-foreground mt-1 text-center whitespace-nowrap">
                      {formatRatio(note.ratio)}
                    </div>
                  </button>
                );
              })}
            </div>
          </div>

          {/* Controls */}
          <div className="flex justify-center gap-4">
            <button
              onClick={addFifth}
              disabled={notes.length >= 12}
              className="btn-play disabled:opacity-50 disabled:cursor-not-allowed"
            >
              <Plus size={20} />
              Moltiplica per 3/2
            </button>
            
            <button
              onClick={reset}
              className="px-6 py-3 rounded-full border-2 border-muted-foreground/30 text-muted-foreground hover:bg-muted transition-colors"
            >
              <RotateCcw size={20} className="inline mr-2" />
              Ricomincia
            </button>
          </div>
        </div>

        {/* Play scale */}
        {notes.length >= 3 && (
          <div className="module-card animate-fade-in">
            <div className="flex items-center justify-between">
              <div>
                <h4 className="font-semibold">Ascolta la scala che hai costruito</h4>
                <p className="text-sm text-muted-foreground">
                  {notes.length} note ordinate per frequenza crescente
                </p>
              </div>
              <button onClick={playScale} className="btn-play">
                <Play size={20} />
                Ascolta
              </button>
            </div>
          </div>
        )}

        <InfoBox type="tip" title="Il ciclo delle quinte">
          Questo metodo si chiama "ciclo delle quinte". Partendo da una nota e 
          moltiplicando sempre per 3/2, puoi generare tutte e 12 le note della 
          scala cromatica! Ci sono voluti secoli per scoprirlo.
        </InfoBox>

        {/* Visual explanation */}
        <div className="grid sm:grid-cols-3 gap-4">
          <div className="module-card text-center">
            <div className="text-3xl font-bold text-accent mb-2">3/2</div>
            <div className="text-sm font-medium">La quinta</div>
            <div className="text-xs text-muted-foreground">
              Il rapporto più consonante dopo l'ottava
            </div>
          </div>
          
          <div className="module-card text-center">
            <div className="text-3xl font-bold text-violet-500 mb-2">÷2</div>
            <div className="text-sm font-medium">Rientro nell'ottava</div>
            <div className="text-xs text-muted-foreground">
              Se il rapporto supera 2, dividi per 2
            </div>
          </div>
          
          <div className="module-card text-center">
            <div className="text-3xl font-bold text-blue-500 mb-2">12</div>
            <div className="text-sm font-medium">Note nella scala</div>
            <div className="text-xs text-muted-foreground">
              7 note + 5 alterazioni (# e ♭)
            </div>
          </div>
        </div>

        <InfoBox type="warning" title="Ma c'è un problema...">
          Se continui per 12 quinte, dovresti tornare esattamente al Do iniziale 
          (7 ottave sopra). Ma 3/2 elevato alla 12 non è uguale a 2 elevato alla 7! 
          Questo "errore" si chiama <strong>virgola pitagorica</strong> e lo 
          esploreremo nel Modulo 11.
        </InfoBox>
      </div>
    </ModuleLayout>
  );
};

export default Module7;